theme: jekyll-theme-minimal

sass:
  sass_dir: assets/styles

exclude: ["vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]
